version: "3.8"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASS
      POSTGRES_DB: DATABASE
    ports:
      - "5432:5432"
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

